image: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda37-x64

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda38-x64


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - echo %PATH%
  - conda --version
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false
  # AppVeyor's Python 3.6 conda installation can't upgrade directly to the
  # newest version without errors. The specified version is the newest one in the
  # CI pipeline logs that was successfully upgraded to from the installed conda.
  - if %PYTHON_VERSION% == 3.6 (conda install conda=4.10.1=py36haa95532_1)
  - conda update -q conda
  - conda install -q conda-build
  - conda info -a
#   # python 3.6 needs specific package versions to work
#   - ps: "
#     if ($env:PYTHON_VERSION -eq \"3.6\"){
#       conda create -q -n test-environment python=$env:PYTHON_VERSION numpy matplotlib conda-forge::pytables ipython pytest seaborn numba nbconvert=5.6.1 jupyter_client=6.1.12 ipykernel pandas pyyaml
#     }
#     else {
#       conda create -q -n test-environment python=$env:PYTHON_VERSION numpy matplotlib conda-forge::pytables ipython pytest seaborn numba nbconvert ipykernel pandas pyyaml
#     }"
#   - activate test-environment
#   - path
  - python -m pip install --upgrade pip
  - pip install pyinstaller
  - pip install git+git://github.com/ramenbytes/phconvert@close-files-on-error
#   - ps: 'if($env:PYTHON_VERSION -eq "2.7"){pip install pathlib}'
#   - python --version
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - dir
#   - python setup.py build
#   - pip install .
#   - python setup.py clean --all

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - dir
  - pyinstaller --hidden-import importlib --debug all --collect-data phconvert gui.py

after_build:
  - 7z a phui-python%PYTHON_VERSION%.zip dist

# before_test:
#   - cd %APPVEYOR_BUILD_FOLDER%\notebooks\data
#   - dir
#   - ps: wget https://ndownloader.figshare.com/files/3350666 -OutFile dsdna_d7d17_50_50_1.set
#   - ps: wget https://ndownloader.figshare.com/files/3350669 -OutFile dsdna_d7d17_50_50_1.spc
#   - ps: wget https://ndownloader.figshare.com/files/3350672 -OutFile Pre.ht3
#   - ps: wget https://ndownloader.figshare.com/files/3350663 -OutFile 0023uLRpitc_NTP_20dT_0.5GndCl.sm
#   - ps: wget https://github.com/Photon-HDF5/phconvert/files/231343/Cy3.Cy5_diff_PIE-FRET.ptu.zip -OutFile Cy3.Cy5_diff_PIE-FRET.ptu.zip
#   - 7z e Cy3.Cy5_diff_PIE-FRET.ptu.zip
#   - ps: wget https://ndownloader.figshare.com/files/6955091 -OutFile 161128_DM1_50pM_pH74.ptu
#   - ps: wget https://ndownloader.figshare.com/files/14828594 -O 20161027_DM1_1nM_pH7_20MHz1.ptu
#   - ps: wget https://ndownloader.figshare.com/files/13675271 -OutFile TestFile_2.ptu
#   - ps: wget https://ndownloader.figshare.com/files/14850533 -O trace_T2_300s_1_coincidence.ptu
#   - ps: wget https://ndownloader.figshare.com/files/14890535 -O nanodiamant_histo.phu
#   - ps: wget https://github.com/dwaithe/FCS_point_correlator/raw/master/focuspoint/topfluorPE_2_1_1_1.pt3 -OutFile topfluorPE_2_1_1_1.pt3
#   - ps: wget https://github.com/Photon-HDF5/phconvert/files/1380341/DNA_FRET_0.5nM.pt3.zip -OutFile DNA_FRET_0.5nM.pt3.zip
#   - 7z e DNA_FRET_0.5nM.pt3.zip
#   - ps: wget https://github.com/Photon-HDF5/phconvert/files/1336330/data.zip -OutFile data.zip
#   - 7z e data.zip

# test_script:
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - py.test -v
#   - cd %APPVEYOR_BUILD_FOLDER%\notebooks
#   - python %APPVEYOR_BUILD_FOLDER%/tests/nbrun.py

# after_test:
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - python setup.py bdist_wheel
#   - echo %PATH%
#   - conda deactivate
#   - activate
#   - path
#   - where python
#   - where git
#   - conda build conda.recipe --python=%PYTHON_VERSION%  --quiet
#   - ps: cp $Env:MINICONDA\conda-bld\win-64\phconvert-*.tar.bz2 $Env:APPVEYOR_BUILD_FOLDER\dist

# artifacts:
#   # bdist_wheel puts your built wheel in the dist directory
#   - path: dist\*
#   - path: notebooks\*-out.ipynb
#   - path: notebooks\*.hdf5

artifacts:
  - path: phui*.zip

skip_tags: true

deploy:
  release: ahh-dont-look-$(APPVEYOR_BUILD_VERSION)
  description: 'Executables for others to test'
  provider: GitHub
  auth_token:
    secure: z+LVern0v7e0nQ2sg0JVc1IT27md9G+7ikI0FiyrxHaW3rMs9cy/ZdfyKj2vpwOX # your encrypted token from GitHub
    artifacts:
      - path: '*.zip'
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    # APPVEYOR_REPO_TAG: true        # deploy on tag push only
